Androapp 4897
dhis2/dhis2-android-real-time-stock-management pull request #7
Opened 2022-08-17 09:06 UTC by mvmmacamo2

End of Library creation

2022-08-17 10:53 UTC, Balcan requested changes
It seems everything is fine.My only comments, as shared in several classes are:
- We should remove commented lines of code and imports. There are several classes.
- We shoud avoid using imports with wildcards.

2022-08-17 10:53 UTC, Balcan commented on app/build.gradle
> +//    implementation project(":stock-managment")
Commented code should be removed

2022-08-17 10:53 UTC, Balcan commented on app/src/main/java/com/baosystems/icrc/psm/di/AppModule.kt
> +//import com.baosystems.icrc.psm.utils.Sdk
Commented imports should be removed

2022-08-17 10:53 UTC, Balcan commented on app/src/main/java/com/baosystems/icrc/psm/di/ServicesModule.kt
> +import org.dhis2.android.rtsm.services.*
Wildcards imports are not allowed by ktlint. It may throw a warning/error message when checked.

2022-08-17 10:53 UTC, Balcan commented on app/src/main/java/com/baosystems/icrc/psm/ui/splashscreen/SplashActivity.java
> +//import com.baosystems.icrc.psm.data.AppConfig;
Remove commented imports

2022-08-17 10:53 UTC, Balcan commented on stock-managment/src/test/java/org/dhis2/android/rtsm/viewmodels/HomeViewModelUnitTest.kt
> +import org.dhis2.android.rtsm.data.*
Ktlint may throw a error/warning message for wildcard imports

2022-08-17 11:04 UTC, andresmr requested changes

2022-08-17 11:04 UTC, andresmr commented on app/build.gradle
> +//        javaCompileOptions.annotationProcessorOptions.arguments['dagger.hilt.disableCrossCompilationRootValidation'] = 'true'
why this is commented? do we need it? if not, please remove this line.

2022-08-17 11:04 UTC, andresmr commented on app/build.gradle
> +    enableExperimentalClasspathAggregation = true
I think, this should be removed given that is in lines 63-66

2022-08-17 11:04 UTC, andresmr commented on app/src/main/AndroidManifest.xml
> +            android:name="org.dhis2.android.rtsm.ui.scanner.ScannerActivity"
The module activities should be moved to the module manifest, if not, it wouldn't work once you import the module in another project

2022-08-17 11:04 UTC, andresmr commented on app/src/main/java/com/baosystems/icrc/psm/ui/splashscreen/SplashActivity.java
> +//import com.baosystems.icrc.psm.data.AppConfig;
please remove commented code

2022-08-17 11:04 UTC, andresmr commented on app/src/main/java/com/baosystems/icrc/psm/ui/splashscreen/SplashActivity.java
> +//import com.baosystems.icrc.psm.utils.ConfigUtils;
please remove commented code

2022-08-17 11:04 UTC, andresmr commented on app/src/main/java/com/baosystems/icrc/psm/ui/sync/SyncActivity.java
> +//import static com.baosystems.icrc.psm.commons.Constants.WORKER_ERROR_MESSAGE_KEY;
please, remove commented code

2022-08-17 11:04 UTC, andresmr commented on app/src/main/java/com/baosystems/icrc/psm/ui/sync/SyncActivity.java
> +//import com.baosystems.icrc.psm.utils.ConfigUtils;
please, remove commented code

2022-08-17 11:04 UTC, andresmr commented on stock-managment/build.gradle
> +//        javaCompileOptions.annotationProcessorOptions.arguments['dagger.hilt.disableCrossCompilationRootValidation'] = 'true'
please, remove commented code

2022-08-17 11:04 UTC, andresmr commented on stock-managment/schemas/org.dhis2.android.rtsm.data.persistence.AppDatabase/1.json
> +{
/schemas folder should be ignored in the .gitignore file

2022-08-17 11:04 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/base/BaseActivity.kt
> +            //.setCaptureActivity(ScannerActivity::class.java)
Why is this commented?

2022-08-17 11:04 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/base/BaseViewModel.kt
> +//import org.dhis2.android.rtsm.BuildConfig
please, remove commented code

2022-08-17 11:14 UTC, andresmr requested changes

2022-08-17 11:14 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/ui/home/HomeActivity.java
> +//import org.hisp.dhis.android.core.organisationunit.OrganisationUnit;
please, remove commented code

2022-08-17 11:14 UTC, andresmr commented on stock-managment/src/main/java/org/dhis2/android/rtsm/utils/ConfigUtils.kt
> +//import org.dhis2.android.rtsm.exceptions.InitializationException
please, remove commented code

2022-08-18 08:01 UTC, Balcan approved these changes

2022-08-18 09:11 UTC, andresmr approved these changes
Good job!

2022-08-18 10:16 UTC, merged